name: agrikredit-development

services:
  farm-ingestion-telegram-bot:
    build:
      context: .
      dockerfile: ./Dockerfile-development
    restart: on-failure
    networks:
      - agrikredit-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  agrikredit-network:
    driver: bridge
